//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player Controler/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""BasicActions"",
            ""id"": ""586535c3-af1b-42d7-9f2a-ec222f0b89fa"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b0d426ba-bafc-4e80-bb78-b12f58e8e85a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.08)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""62929b8f-73ca-4973-8f7d-74e4dba5c31a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BasicAttack"",
                    ""type"": ""Button"",
                    ""id"": ""39d03e8c-25e2-4a44-8794-6b86f2d8e6b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpellAttack"",
                    ""type"": ""Button"",
                    ""id"": ""b7dc13fd-3675-40a1-b8f0-179522c8d5e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""14572b06-0b28-4703-8301-7ed08c33fb03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""f7e9f793-8e32-49a7-9c20-8ff9c4fc0dcd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SavePoint"",
                    ""type"": ""Button"",
                    ""id"": ""ae0c31b9-d93b-4463-ad81-32a369f70e65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMap"",
                    ""type"": ""Button"",
                    ""id"": ""47d2ad70-de48-4d88-925d-b3fc6e2e3fb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClosePopup"",
                    ""type"": ""Button"",
                    ""id"": ""cb26db5b-2e6d-4156-a6ba-558b82897b04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3fd18762-d6a4-484a-9806-eea2a8841f31"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4645d12f-8f95-4179-933b-4ded4b4be0ba"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d97b425e-fcef-45d1-bdd4-60dd5966c965"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpellAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bde7d55-4ccc-43a3-842d-77d69765cbb4"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpellAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8af8b51-b44e-40e0-b828-804adead24df"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpellAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9954d26-4fd5-436b-9597-d9378d7cd2f5"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpellAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7a49a404-172a-4c83-9b02-2e1c98b48f64"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""27b92977-226a-494a-b91d-f07bad1a4679"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0ac87d90-3f60-4a5f-9318-6722400ebb2c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""58a4e8f3-f689-4b66-a9c7-472fb0295d39"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D vector"",
                    ""id"": ""1866a399-fca7-4ded-b572-e47a114e3ba8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d59fa72c-9a24-4ce8-8919-6fab18ef6c5a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a72d23d4-953e-4d94-968b-ebbd20930040"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c62bcd7c-c863-4f19-9d91-9f5b3803866c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2aa82a7c-8975-43fb-b224-23cef7375d1e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""48f61888-aabf-4c01-a51e-dc754fcc98d9"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4d83ea90-9cd6-49f3-97c5-164a288c8d84"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f7ad19c2-b9d0-43ee-b872-e94af42ea9ff"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a5bd5f7-a24e-450f-8a85-022d79948226"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34ec8852-4375-4536-b360-5d948284616f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BasicAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bec37422-2f98-4bb1-9f66-373b928b5cd6"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BasicAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16abcc4c-b3c1-4ca2-aef4-01c5124e5a0e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1ca5384-084a-44b6-9bd0-e09af3aa3c82"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d56f4777-99cf-485c-a4dd-b9286fc16a67"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SavePoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fe8ba4c-0933-4cc8-bf2e-459a9710b16f"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SavePoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d58b3ec7-6e06-42ea-b596-54d8967cdeb8"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fdd524b-63b8-4fb2-83d2-1c673b306601"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09f669cd-c7b6-424c-bf89-3ba4df1cd2ef"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClosePopup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b988ccba-3a63-4f91-92bf-d88e02a40716"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClosePopup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""0d62bb39-2999-4948-8f42-5dc45e14e809"",
            ""actions"": [
                {
                    ""name"": ""MoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""e741b71e-097c-40d5-b675-6c2f16ad7309"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""8520f506-5b90-43ba-9514-c98a47bdd6ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""8da44789-1783-44df-ab11-221cc1732e6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""10dabe59-ddf7-4a44-b968-ac296f77fb94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""097b41dd-5277-4331-9dfb-e87446873c4c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1043fde1-e94a-4bbc-9a2d-4265b7d5d2bf"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7d22873-8604-43ed-aada-c3d799ed9168"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""796c3dee-bf94-4a4f-ba81-25b24e18af9f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c36e00c2-4e27-48c3-8213-0140d5f97791"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9ff148d-406c-48bc-8bb7-d08d205ecbd3"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec966cd2-6c45-4b87-bdb9-53eb98811acb"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e119c7ae-be98-4366-8b32-6e5ffa97269b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""329fb654-3f41-42db-a86a-49f5191010a5"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BasicActions
        m_BasicActions = asset.FindActionMap("BasicActions", throwIfNotFound: true);
        m_BasicActions_Jump = m_BasicActions.FindAction("Jump", throwIfNotFound: true);
        m_BasicActions_Move = m_BasicActions.FindAction("Move", throwIfNotFound: true);
        m_BasicActions_BasicAttack = m_BasicActions.FindAction("BasicAttack", throwIfNotFound: true);
        m_BasicActions_SpellAttack = m_BasicActions.FindAction("SpellAttack", throwIfNotFound: true);
        m_BasicActions_Dash = m_BasicActions.FindAction("Dash", throwIfNotFound: true);
        m_BasicActions_Escape = m_BasicActions.FindAction("Escape", throwIfNotFound: true);
        m_BasicActions_SavePoint = m_BasicActions.FindAction("SavePoint", throwIfNotFound: true);
        m_BasicActions_ToggleMap = m_BasicActions.FindAction("ToggleMap", throwIfNotFound: true);
        m_BasicActions_ClosePopup = m_BasicActions.FindAction("ClosePopup", throwIfNotFound: true);
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_MoveDown = m_Camera.FindAction("MoveDown", throwIfNotFound: true);
        m_Camera_MoveUp = m_Camera.FindAction("MoveUp", throwIfNotFound: true);
        m_Camera_MoveLeft = m_Camera.FindAction("MoveLeft", throwIfNotFound: true);
        m_Camera_MoveRight = m_Camera.FindAction("MoveRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BasicActions
    private readonly InputActionMap m_BasicActions;
    private IBasicActionsActions m_BasicActionsActionsCallbackInterface;
    private readonly InputAction m_BasicActions_Jump;
    private readonly InputAction m_BasicActions_Move;
    private readonly InputAction m_BasicActions_BasicAttack;
    private readonly InputAction m_BasicActions_SpellAttack;
    private readonly InputAction m_BasicActions_Dash;
    private readonly InputAction m_BasicActions_Escape;
    private readonly InputAction m_BasicActions_SavePoint;
    private readonly InputAction m_BasicActions_ToggleMap;
    private readonly InputAction m_BasicActions_ClosePopup;
    public struct BasicActionsActions
    {
        private @PlayerInputs m_Wrapper;
        public BasicActionsActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_BasicActions_Jump;
        public InputAction @Move => m_Wrapper.m_BasicActions_Move;
        public InputAction @BasicAttack => m_Wrapper.m_BasicActions_BasicAttack;
        public InputAction @SpellAttack => m_Wrapper.m_BasicActions_SpellAttack;
        public InputAction @Dash => m_Wrapper.m_BasicActions_Dash;
        public InputAction @Escape => m_Wrapper.m_BasicActions_Escape;
        public InputAction @SavePoint => m_Wrapper.m_BasicActions_SavePoint;
        public InputAction @ToggleMap => m_Wrapper.m_BasicActions_ToggleMap;
        public InputAction @ClosePopup => m_Wrapper.m_BasicActions_ClosePopup;
        public InputActionMap Get() { return m_Wrapper.m_BasicActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BasicActionsActions set) { return set.Get(); }
        public void SetCallbacks(IBasicActionsActions instance)
        {
            if (m_Wrapper.m_BasicActionsActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnJump;
                @Move.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnMove;
                @BasicAttack.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnBasicAttack;
                @BasicAttack.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnBasicAttack;
                @BasicAttack.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnBasicAttack;
                @SpellAttack.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSpellAttack;
                @SpellAttack.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSpellAttack;
                @SpellAttack.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSpellAttack;
                @Dash.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnDash;
                @Escape.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnEscape;
                @SavePoint.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSavePoint;
                @SavePoint.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSavePoint;
                @SavePoint.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSavePoint;
                @ToggleMap.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnToggleMap;
                @ToggleMap.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnToggleMap;
                @ToggleMap.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnToggleMap;
                @ClosePopup.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnClosePopup;
                @ClosePopup.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnClosePopup;
                @ClosePopup.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnClosePopup;
            }
            m_Wrapper.m_BasicActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @BasicAttack.started += instance.OnBasicAttack;
                @BasicAttack.performed += instance.OnBasicAttack;
                @BasicAttack.canceled += instance.OnBasicAttack;
                @SpellAttack.started += instance.OnSpellAttack;
                @SpellAttack.performed += instance.OnSpellAttack;
                @SpellAttack.canceled += instance.OnSpellAttack;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
                @SavePoint.started += instance.OnSavePoint;
                @SavePoint.performed += instance.OnSavePoint;
                @SavePoint.canceled += instance.OnSavePoint;
                @ToggleMap.started += instance.OnToggleMap;
                @ToggleMap.performed += instance.OnToggleMap;
                @ToggleMap.canceled += instance.OnToggleMap;
                @ClosePopup.started += instance.OnClosePopup;
                @ClosePopup.performed += instance.OnClosePopup;
                @ClosePopup.canceled += instance.OnClosePopup;
            }
        }
    }
    public BasicActionsActions @BasicActions => new BasicActionsActions(this);

    // Camera
    private readonly InputActionMap m_Camera;
    private ICameraActions m_CameraActionsCallbackInterface;
    private readonly InputAction m_Camera_MoveDown;
    private readonly InputAction m_Camera_MoveUp;
    private readonly InputAction m_Camera_MoveLeft;
    private readonly InputAction m_Camera_MoveRight;
    public struct CameraActions
    {
        private @PlayerInputs m_Wrapper;
        public CameraActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveDown => m_Wrapper.m_Camera_MoveDown;
        public InputAction @MoveUp => m_Wrapper.m_Camera_MoveUp;
        public InputAction @MoveLeft => m_Wrapper.m_Camera_MoveLeft;
        public InputAction @MoveRight => m_Wrapper.m_Camera_MoveRight;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void SetCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterface != null)
            {
                @MoveDown.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveDown;
                @MoveDown.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveDown;
                @MoveDown.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveDown;
                @MoveUp.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveUp;
                @MoveUp.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveUp;
                @MoveUp.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveUp;
                @MoveLeft.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveLeft;
                @MoveRight.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveRight;
            }
            m_Wrapper.m_CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveDown.started += instance.OnMoveDown;
                @MoveDown.performed += instance.OnMoveDown;
                @MoveDown.canceled += instance.OnMoveDown;
                @MoveUp.started += instance.OnMoveUp;
                @MoveUp.performed += instance.OnMoveUp;
                @MoveUp.canceled += instance.OnMoveUp;
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
            }
        }
    }
    public CameraActions @Camera => new CameraActions(this);
    public interface IBasicActionsActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnBasicAttack(InputAction.CallbackContext context);
        void OnSpellAttack(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnSavePoint(InputAction.CallbackContext context);
        void OnToggleMap(InputAction.CallbackContext context);
        void OnClosePopup(InputAction.CallbackContext context);
    }
    public interface ICameraActions
    {
        void OnMoveDown(InputAction.CallbackContext context);
        void OnMoveUp(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
    }
}
